version: "3.9"

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src
    volumes:
      - ./api:/src              # ton code .NET monté en live
      - api_bin:/src/bin        # évite d’écrire bin/obj sur l’hôte
      - api_obj:/src/obj
      - dotnet_nuget:/root/.nuget/packages
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"   # fiable sous Windows/WSL
    ports:
      - "8080:8080"
    command: ["dotnet", "watch", "run", "--non-interactive"]
    networks:
      - web

  front:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./front:/app            # ton code React monté en live
      - front_node:/app/node_modules
    environment:
      HOST: "0.0.0.0"
      CHOKIDAR_USEPOLLING: "true"   # fiabilise le watch
      WATCHPACK_POLLING: "true"
      VITE_API_URL: "http://localhost:8080"  # appel API côté navigateur
    ports:
      - "5173:5173"
    command: sh -c "npm i && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - api
    networks:
      - web

networks:
  web:

volumes:
  api_bin:
  api_obj:
  dotnet_nuget:
  front_node:
