version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
    networks:
      - web

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "/api"
    depends_on:
      - api
    ports:
      - "8080:80"
    networks:
      - web

networks:
  web:
