// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Data.Migrations
{
    [DbContext(typeof(PortyDbContext))]
    [Migration("20251107233506_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Data.Models.Buisness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("T_BUISNESS", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.Career", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Comments")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("COMMENTS")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("END_DATE")
                        .HasColumnOrder(3);

                    b.Property<Guid>("RefBuisness")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_BUISNESS")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("START_DATE")
                        .HasColumnOrder(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("TITLE")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("RefBuisness");

                    b.ToTable("T_CAREER", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.CareerSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("RefCareer")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_CAREER")
                        .HasColumnOrder(2);

                    b.Property<Guid>("RefSkill")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_SKILL")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("RefCareer");

                    b.HasIndex("RefSkill");

                    b.ToTable("T_CAREER_SKILL", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("T_CATEGORY", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATE")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(2);

                    b.Property<string>("Url")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("URL")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.ToTable("T_CERTIFICATE", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CODE")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("T_LANGUAGE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "fr",
                            Name = "Français"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("api.Data.Models.MailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(5)
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_AT")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("T_MAIL_TEMPLATE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7961e375-87e8-417a-8c67-5717c31d84f1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mail envoyé lors de la création du compte avec un token pour valider le compte.",
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ConfirmationInscription"
                        });
                });

            modelBuilder.Entity("api.Data.Models.MailTemplateTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HTML_BODY")
                        .HasColumnOrder(4);

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("LOCALE")
                        .HasColumnOrder(2);

                    b.Property<Guid>("RefTemplate")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_TEMPLATE")
                        .HasColumnOrder(7);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SUBJECT")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Locale");

                    b.HasIndex("RefTemplate", "Locale")
                        .IsUnique();

                    b.ToTable("T_MAIL_TEMPLATE_TRANSLATION", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(2);

                    b.Property<string>("Url")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("URL")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("T_PROJECT", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.ProjectSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("RefProject")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_PROJECT")
                        .HasColumnOrder(2);

                    b.Property<Guid>("RefSkill")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_SKILL")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("RefProject");

                    b.HasIndex("RefSkill");

                    b.ToTable("T_PROJECT_SKILL", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("T_ROLE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("74737d58-a69f-4df7-bf9a-777297a4d6d6"),
                            Description = "Utilisateur standard",
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("a3a52661-a5a1-4d13-a765-48543eb06cfe"),
                            Description = "Administrateur",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("api.Data.Models.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("T_SCHOOL", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Certification")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("CERTIFICATION")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(2);

                    b.Property<Guid>("RefCategory")
                        .HasMaxLength(128)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_CATEGORY")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("RefCategory");

                    b.ToTable("T_SKILL", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Comments")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("COMMENTS")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("END_DATE")
                        .HasColumnOrder(3);

                    b.Property<Guid>("RefSchool")
                        .HasMaxLength(128)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_SCHOOL")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("START_DATE")
                        .HasColumnOrder(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("TITLE")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("RefSchool");

                    b.ToTable("T_STUDY", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(9)
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("EMAIL")
                        .HasColumnOrder(5);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FIRSTNAME")
                        .HasColumnOrder(2);

                    b.Property<bool?>("IsEmailValidated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_EMAIL_VALIDATED")
                        .HasColumnOrder(10);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LASTNAME")
                        .HasColumnOrder(3);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("PASSWORD")
                        .HasColumnOrder(6);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE_NUMBER")
                        .HasColumnOrder(4);

                    b.Property<Guid>("RefRole")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_ROLE")
                        .HasColumnOrder(8);

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("SALT")
                        .HasColumnOrder(7);

                    b.Property<Guid?>("TokenAccountCreated")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TOKEN_ACCOUNT_CREATED")
                        .HasColumnOrder(11);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RefRole");

                    b.ToTable("T_USER", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.Career", b =>
                {
                    b.HasOne("api.Data.Models.Buisness", "Buisness")
                        .WithMany("Careers")
                        .HasForeignKey("RefBuisness")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buisness");
                });

            modelBuilder.Entity("api.Data.Models.CareerSkill", b =>
                {
                    b.HasOne("api.Data.Models.Career", "Career")
                        .WithMany("CareerSkills")
                        .HasForeignKey("RefCareer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Data.Models.Skill", "Skill")
                        .WithMany("CareerSkills")
                        .HasForeignKey("RefSkill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Career");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("api.Data.Models.MailTemplateTranslation", b =>
                {
                    b.HasOne("api.Data.Models.Language", null)
                        .WithMany()
                        .HasForeignKey("Locale")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("api.Data.Models.MailTemplate", "Template")
                        .WithMany("Translations")
                        .HasForeignKey("RefTemplate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("api.Data.Models.ProjectSkill", b =>
                {
                    b.HasOne("api.Data.Models.Project", "Project")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("RefProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Data.Models.Skill", "Skill")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("RefSkill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("api.Data.Models.Skill", b =>
                {
                    b.HasOne("api.Data.Models.Category", "Category")
                        .WithMany("Skills")
                        .HasForeignKey("RefCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("api.Data.Models.Study", b =>
                {
                    b.HasOne("api.Data.Models.School", "School")
                        .WithMany("Studies")
                        .HasForeignKey("RefSchool")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("api.Data.Models.User", b =>
                {
                    b.HasOne("api.Data.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RefRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_T_USER_refRole__T_ROLE_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("api.Data.Models.Buisness", b =>
                {
                    b.Navigation("Careers");
                });

            modelBuilder.Entity("api.Data.Models.Career", b =>
                {
                    b.Navigation("CareerSkills");
                });

            modelBuilder.Entity("api.Data.Models.Category", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("api.Data.Models.MailTemplate", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("api.Data.Models.Project", b =>
                {
                    b.Navigation("ProjectSkills");
                });

            modelBuilder.Entity("api.Data.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("api.Data.Models.School", b =>
                {
                    b.Navigation("Studies");
                });

            modelBuilder.Entity("api.Data.Models.Skill", b =>
                {
                    b.Navigation("CareerSkills");

                    b.Navigation("ProjectSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
