apiVersion: v1
kind: Service
metadata:
  name: ${FRONT_APP_NAME}
  labels:
    app: ${FRONT_APP_NAME}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: porty-front
